<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>Restaurante</title>
    <meta charset="utf-8" />
    <base href="<?php echo $this->baseUrl(); ?>" />
    <!--<link href='https://fonts.googleapis.com/css?family=Roboto:400,700,500' rel='stylesheet' type='text/css'>-->
    <link rel="stylesheet" href="/css/blog.css" />
  </head>

  <body>
    <ul id="menu">
        <?php echo $this->navigation(); ?>
    </ul>
    <ul id="breadcrumb">
      Você esta em: <?php
      echo $this->navigation()->breadcrumbs()
              ->setMinDepth(null) // start at level 0
              ->setMaxDepth(1) // stop at level 1
              ->setSeparator('&raquo;')
      ;
      ?>
    </ul>
    <div id="content"><?php echo $this->layout()->content ?></div>
  </body>

</html>